name: Run Smoke Tests (Manual)

on:
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Run Smoke Tests
        run: mvn clean test -Psmoke

      - name: Debug Network
        run: ping selenium-hub || curl http://selenium-hub:4444/status
