name: Run Smoke Tests (Manual)

on:
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Run Smoke Tests
        run: mvn clean test -Psmoke
